```{r}



library(tidyverse)
library(Lahman)

myteams <- Teams %>%
  filter(yearID > 2000) %>%
  select(teamID, yearID, lgID, G, W, L, R, RA)
myteams %>%
  tail()

myteams <- myteams %>%
  mutate(RD = R-RA, Wpct = W / (W + L))

run_diff <- ggplot(myteams, aes(x = RD, y = Wpct)) +
  geom_point() +
  scale_x_continuous("Run Differential") +
  scale_y_continuous("Winning Percentage")
run_diff

linfit <- lm(Wpct~RD, data = myteams)
linfit

run_diff + geom_smooth(method = "lm", se = FALSE)


library(broom)

my_teams_aug <- augment(linfit, data = myteams)

base_plot <- ggplot(my_teams_aug, aes(x = RD, y = .resid)) +
  geom_point(alpha = 0.3) +
  geom_hline(yintercept = 0, linetype = 3) +
  xlab("Run Differential") + ylab("Residual")

highlight_teams <- my_teams_aug %>%
  arrange(desc(abs(.resid))) %>%
  head(4)

library(ggrepel)

base_plot +
  geom_point(data = highlight_teams) +
  geom_text_repel(data = highlight_teams, aes(label = paste(teamID, yearID)))

resid_summary <- my_teams_aug %>%
  summarize(N = n(), avg = mean(.resid),
            RMSE = sqrt(mean(.resid^2)))
resid_summary


##Pythagorean Formula

myteams <- myteams %>%
  mutate(Wpct_pyth = R^2 / (R^2 + RA^2))

myteams <- myteams %>%
  mutate(residuals_pyth = Wpct - Wpct_pyth)

myteams %>%
  summarize(rmse = sqrt(mean(residuals_pyth^2)))

pyth_plot <- ggplot(myteams, aes(x = Wpct_pyth, y = Wpct)) +
  geom_point() +
  scale_x_continuous("Pythagorean Diff") +
  scale_y_continuous("Winning Percentage")
pyth_plot

pyth_plot + geom_smooth(method = "lm", se = FALSE)


##Pythagoran Exponent Estimation

myteams <- myteams %>%
  mutate(logWratio = log(W/L),
         logRratio = log(R/RA))
pythfit <- lm(logWratio~0 + logRratio, data = myteams)
pythfit
```



       RUN DIFF      PYTH
      Slope  RMSE   K  RMSE
60's  .0006  .0235 1.88 .0250   

70's  .0006  .0251 1.72 .0275

80's  .0006  .0260 1.94 .0246

90's  .0006  .0260 1.90 .0252

00's  .0006  .0253 1.84 .0261



```{r}
library(tidyverse)
library(Lahman)

myteams <- Teams %>%
  filter(yearID > 2000) %>%
  select(teamID, yearID, lgID, G, W, L, R, RA)
myteams %>%
  tail()

myteams <- myteams %>%
  mutate(RD = R-RA, Wpct = W / (W + L))

run_diff <- ggplot(myteams, aes(x = RD, y = Wpct)) +
  geom_point() +
  scale_x_continuous("Run Differential") +
  scale_y_continuous("Winning Percentage")
run_diff

linfit <- lm(Wpct~RD, data = myteams)
linfit

run_diff + geom_smooth(method = "lm", se = FALSE)


library(broom)

my_teams_aug <- augment(linfit, data = myteams)

base_plot <- ggplot(my_teams_aug, aes(x = RD, y = .resid)) +
  geom_point(alpha = 0.3) +
  geom_hline(yintercept = 0, linetype = 3) +
  xlab("Run Differential") + ylab("Residual")

highlight_teams <- my_teams_aug %>%
  arrange(desc(abs(.resid))) %>%
  head(4)

library(ggrepel)

base_plot +
  geom_point(data = highlight_teams) +
  geom_text_repel(data = highlight_teams, aes(label = paste(teamID, yearID)))

resid_summary <- my_teams_aug %>%
  summarize(N = n(), avg = mean(.resid),
            RMSE = sqrt(mean(.resid^2)))
resid_summary


##Pythagorean Formula

myteams <- myteams %>%
  mutate(Wpct_pyth = R^2 / (R^2 + RA^2))

myteams <- myteams %>%
  mutate(residuals_pyth = Wpct - Wpct_pyth)

myteams %>%
  summarize(rmse = sqrt(mean(residuals_pyth^2)))

pyth_plot <- ggplot(myteams, aes(x = Wpct_pyth, y = Wpct)) +
  geom_point() +
  scale_x_continuous("Pythagorean Diff") +
  scale_y_continuous("Winning Percentage")
pyth_plot

pyth_plot + geom_smooth(method = "lm", se = FALSE)


##Pythagoran Exponent Estimation

myteams <- myteams %>%
  mutate(logWratio = log(W/L),
         logRratio = log(R/RA))
pythfit <- lm(logWratio~0 + logRratio, data = myteams)
pythfit

##Pythagorean Outliers

library(RCurl)
x <- getURL("https://raw.githubusercontent.com/maxtoki/baseball_R/master/data/game_log_header.csv")
glheaders <- read.csv(text = x)


gl2011 <- read_csv("GL2011.csv", col_names = names(glheaders),
                   na = character())


BOS2011 <- gl2011 %>%
  filter(HomeTeam == "BOS" | VisitingTeam == "BOS") %>%
  select(VisitingTeam, HomeTeam, VisitorRunsScored, HomeRunsScore)
head(BOS2011)

BOS2011 <- BOS2011 %>%
  mutate(ScoreDiff = ifelse(HomeTeam == "BOS", 
                            HomeRunsScore - VisitorRunsScored, 
                            VisitorRunsScored - HomeRunsScore),
         W = ScoreDiff > 0)

library(skimr)
BOS2011 %>%
  group_by(W) %>%
  skim(ScoreDiff)

results <- gl2011 %>%
  select(VisitingTeam, HomeTeam,
         VisitorRunsScored, HomeRunsScore) %>%
  mutate(winner = ifelse(HomeRunsScore > VisitorRunsScored,
                         HomeTeam, VisitingTeam),
         diff = abs(VisitorRunsScored - HomeRunsScore))

one_run_wins <- results %>%
  filter(diff == 1) %>%
  group_by(winner) %>%
  summarize(one_run_w = n())

teams2011 <- myteams %>%
  filter(yearID == 2011) %>%
  mutate(teamID = ifelse(teamID == "LAA", "ANA",
                         as.character(teamID))) %>%
  inner_join(one_run_wins, by = c("teamID" = "winner"))

ggplot(data = teams2011, aes(x = one_run_w, y = residuals_pyth)) +
  geom_point() +
  geom_text_repel(aes(label = teamID)) +
  xlab("One run wins") + ylab("Pythagorean Residuals")
###Incremental Runs per win

D(expression(G*R^2/(R^2 +RA^2)), "R")

IR <- function(RS = 5, RA = 5) {
  (RS^2 + RA^2)^2/(2*RS*RA^2)
}

ir_table <- expand.grid(RS = seq(3, 6, .5),
                        RA = seq(3, 6, .5))
head(ir_table)

tail(ir_table)

ir_table %>%
  mutate(IRW = IR(RS,RA)) %>%
  spread(key = RA, value = IRW, sep = "=") %>%
  round(1)

```

